export const MIN_SIZE = 1
export const MAX_SIZE = 100000000
export const TIPS = `please input an interger between ${MIN_SIZE} to ${MAX_SIZE}`
export const STATISTIC_MIN_SIZE = 1000
export const STATISTIC_MAX_SIZE = 500000
export const RUN_SINGE = 'runSingleIntersection'
export const RUN_MULTIPLE = 'runMultipleIntersection'
export const SINGLE_RESULT = 'singleIntersectionResult'
export const MULTIPLE_RESULT = 'multipleIntersectionResult'
export const ERROR_FLAG = 'error'
export const EXPERIMENT_TIMES = 30
